# Generated by Django 4.1 on 2023-01-11 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0003_remove_studentprofile_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='HistoricalTeacherProfile',
        ),
        migrations.DeleteModel(
            name='TeacherProfile',
        ),
    ]
