# Generated by Django 4.1 on 2023-01-11 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0004_remove_teacherprofile_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ownerprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='HistoricalOwnerProfile',
        ),
        migrations.DeleteModel(
            name='OwnerProfile',
        ),
    ]
